name: PR

on:
  pull_request:

env:
  CI: true
  PNPM_VERSION: 8.6.7

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: true
